version: "3.8"
services:
  # Postgres / Multiple Databases
  postgres:
    restart: always
    container_name: postgres
    image: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: book_crud_db
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready","-q","-d", "book_crud_db", "-U","postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - global-net
  # Django Server
  server:
    restart: always
    container_name: server
    build:
      context: .
      dockerfile: ./deploy/docker/server.Dockerfile
    env_file:
      - .dev.env
    ports:
      - "8100:8100"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - static-data:/app/backend/static
      - media-data:/app/backend/media
    networks:
      - global-net
networks:
  global-net:
    driver: bridge
volumes:
  postgres-data: { }
  static-data: { }
  media-data: { }